### ISSUE TITLE
Visual Studio 2022 Bug

### ISSUE THREAD

**Issue by OwariSync** [viliger2/BRC_CharacterAPI#4]
"The SDK 'Microsoft.NET.Sdk' specified could not be found." I followed the guide 1:1, and reinstalled several times. I tried using Visual Studio 2019 as well, and it still gave this same error.

**Comment by viliger2** [comment]
Try ticking .NET SDK under Individual Components and make sure that everything under 4.6.2 is ticked.
![image](https://github.com/viliger2/BRC_CharacterAPI/assets/53978306/ac6e85e5-355e-4d8d-8975-6cb37cf8acdf)

**Comment by OwariSync** [comment]
Thanks, that solved it!
